# Highly divisible triangular number
#
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?



source("largest_prime_factor.r")
primes <- sieve(100)

factors <- function(x, prime = prime) {
    m <- length(prime)
    fac.count <- numeric(m)
    for (i in 1 : m) {
        while (x %% prime[i] == 0) {
            fac.count[i] <- fac.count[i] + 1
            x = x / prime[i]
        }
        if (x == 1)
            break
    }
    return(prod(fac.count + 1))
}

i <- 0
divisors <- 0
while (divisors < 500) {
    i <- i + 1
    triangle <- (i * (i + 1)) / 2
    divisors <- factors(triangle, primes)
}

print(triangle)



##
